nginx:
  image: "nginx:1.9"
  ports:
    - 80:80
  links:
    - three_game:three_game
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  volumes_from:
    - three_game:ro

three_game:
  image: "qiannanxu/three_game"
  volumes:
      - datavolume:/app
